# Generated by Django 4.1.4 on 2022-12-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='nbrechild',
            field=models.IntegerField(),
        ),
    ]
