# Generated by Django 4.1.4 on 2023-01-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_alter_employe_nbrechild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='description',
            field=models.CharField(max_length=255, verbose_name='test'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom Departement'),
        ),
    ]
