# Generated by Django 4.1.4 on 2023-01-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_alter_departement_description_alter_departement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='departement',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
