# Generated by Django 4.1.4 on 2023-01-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0005_alter_departement_description_alter_departement_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='soft_deleting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employe',
            name='soft_deleting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lieuemploi',
            name='soft_deleting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poste',
            name='soft_deleting',
            field=models.BooleanField(default=False),
        ),
    ]
