# Generated by Django 4.1.4 on 2023-01-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0006_departement_soft_deleting_employe_soft_deleting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='email',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
