# Generated by Django 4.1.4 on 2023-01-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0007_employe_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='email',
            new_name='emailemp',
        ),
    ]
