# Generated by Django 4.1.4 on 2023-01-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0008_rename_email_employe_emailemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='contacturgence',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employe',
            name='phone1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employe',
            name='phone2',
            field=models.CharField(max_length=100),
        ),
    ]
