# Generated by Django 4.1.4 on 2023-02-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0009_alter_employe_contacturgence_alter_employe_phone1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='soft_deleting',
            field=models.BooleanField(default=False),
        ),
    ]
