# Generated by Django 4.1.4 on 2023-02-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0010_account_soft_deleting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='genre',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=5),
        ),
    ]
