# Generated by Django 4.1.4 on 2023-04-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0011_alter_employe_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='faceid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
