# Generated by Django 4.2.1 on 2023-05-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0012_employe_faceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
