# Generated by Django 4.2.1 on 2023-06-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0014_account_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('E', 'Employe'), ('R', 'Ressources Humaines'), ('AD', 'Administrateur')], default='E', max_length=5),
        ),
    ]
