# Generated by Django 4.2.1 on 2023-06-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0015_alter_account_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='photoemp',
            field=models.ImageField(blank=True, upload_to='medias/employe'),
        ),
    ]
