# Generated by Django 4.2.1 on 2023-06-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0016_employe_photoemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='photoemp',
            field=models.ImageField(blank=True, null=True, upload_to='medias/employe'),
        ),
    ]
