# Generated by Django 4.2.1 on 2023-06-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0018_alter_employe_photoemp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='nationnalite',
        ),
    ]
