# Generated by Django 4.2.1 on 2023-06-25 18:06

from django.db import migrations, models
import employe.models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0019_remove_employe_nationnalite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='photoemp',
            field=models.ImageField(blank=True, default='media/employe/photo_default-1', null=True, upload_to=employe.models.renameImage),
        ),
    ]
