# Generated by Django 4.2.3 on 2023-07-06 16:26

from django.db import migrations, models
import employe.models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0020_alter_employe_photoemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='photoemp',
            field=models.ImageField(blank=True, default='employe/photo_default-1.jpg', null=True, upload_to=employe.models.renameImage),
        ),
    ]
