# Generated by Django 4.2.1 on 2023-06-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='soft_deleting',
            field=models.BooleanField(default=False),
        ),
    ]
