# Generated by Django 4.2.1 on 2023-05-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0002_time_pointage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointage',
            name='is_out',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
