# Generated by Django 4.2.1 on 2023-05-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0003_pointage_date_time_pointage_is_out_delete_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='datedebut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='datefin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
