# Generated by Django 4.2.1 on 2023-05-21 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0004_alter_presence_datedebut_alter_presence_datefin'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
