# Generated by Django 4.2.4 on 2023-08-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0005_presence_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='temptravail',
        ),
        migrations.AddField(
            model_name='presence',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
