# Generated by Django 4.1.4 on 2023-02-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0002_contrat_soft_deleting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='datedebut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='datefin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='typecontrat',
            field=models.CharField(choices=[('STG', 'Stage'), ('CDD', 'Contrat à durée déterminé'), ('CDI', 'Contrat à durée indéterminé')], max_length=40),
        ),
    ]
