# Generated by Django 4.1.4 on 2023-02-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0003_alter_contrat_datedebut_alter_contrat_datefin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='duree',
        ),
    ]
