# Generated by Django 4.1.4 on 2023-03-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conges',
            name='duree',
        ),
        migrations.AddField(
            model_name='conges',
            name='soft_deleting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conges',
            name='etatconges',
            field=models.CharField(choices=[('NEW', 'Nouveau'), ('ATT', 'Attente'), ('VAL', 'Validé'), ('REJ', 'Rejeté')], default='NEW', max_length=40),
        ),
    ]
