# Generated by Django 4.1.4 on 2023-03-26 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0002_remove_conges_duree_conges_soft_deleting_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeconges',
            old_name='desciption',
            new_name='description',
        ),
    ]
