# Generated by Django 4.1.4 on 2023-05-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0003_rename_desciption_typeconges_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conges',
            old_name='desciption',
            new_name='description',
        ),
    ]
